aloha.init()
config = aloha.create_config()
flags = aloha.WINDOWED | aloha.OPENGL_3_0
aloha.set_new_display_flags(flags)
--aloha.set_new_window_position(100, 100)
x, y = aloha.get_new_window_position()
print(x, y)
display = aloha.create_display(1024, 768)
a, b = aloha.get_window_position(display)
print(a, b)
aloha.destroy_display(display)
aloha.destroy_config(config)
aloha.uninstall_system()
